// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) KALEIDOS INC

import React from 'react';

// Icon size constants
const ICON_SIZE_L = 32;
const ICON_SIZE_M = 16;
const ICON_SIZE_S = 12;

export type IconSize = 's' | 'm' | 'l';

export interface IconProps {
  iconId: string;
  size?: IconSize;
  class?: string;
}

export function Icon({ iconId, size = 'm', class: className }: IconProps): JSX.Element {
  const width = size === 'l' ? ICON_SIZE_L : size === 's' ? ICON_SIZE_S : ICON_SIZE_M;
  const height = width;
  const offset = (size === 's' || size === 'm') ? (ICON_SIZE_M - width) / 2 : 0;

  const iconUrl = `#icon-${iconId}`;

  return React.createElement(
    'svg',
    {
      className,
      width,
      height,
      x: offset,
      y: offset
    },
    React.createElement('use', { href: iconUrl })
  );
}

// Icon ID constants - These should be generated from actual icon definitions
export const ICON_ID = {
  absolute: 'absolute',
  add: 'add',
  alignBottom: 'align-bottom',
  alignContentColumnAround: 'align-content-column-around',
  alignContentColumnBetween: 'align-content-column-between',
  alignContentColumnCenter: 'align-content-column-center',
  alignContentColumnEnd: 'align-content-column-end',
  alignContentColumnEvenly: 'align-content-column-evenly',
  alignContentColumnStart: 'align-content-column-start',
  alignContentColumnStretch: 'align-content-column-stretch',
  alignContentRowAround: 'align-content-row-around',
  alignContentRowBetween: 'align-content-row-between',
  alignContentRowCenter: 'align-content-row-center',
  alignContentRowEnd: 'align-content-row-end',
  alignContentRowEvenly: 'align-content-row-evenly',
  alignContentRowStart: 'align-content-row-start',
  alignContentRowStretch: 'align-content-row-stretch',
  alignHorizontalCenter: 'align-horizontal-center',
  alignItemsColumnCenter: 'align-items-column-center',
  alignItemsColumnEnd: 'align-items-column-end',
  alignItemsColumnStart: 'align-items-column-start',
  alignItemsRowCenter: 'align-items-row-center',
  alignItemsRowEnd: 'align-items-row-end',
  alignItemsRowStart: 'align-items-row-start',
  alignLeft: 'align-left',
  alignRight: 'align-right',
  alignSelfColumnBottom: 'align-self-column-bottom',
  alignSelfColumnCenter: 'align-self-column-center',
  alignSelfColumnStretch: 'align-self-column-stretch',
  alignSelfColumnTop: 'align-self-column-top',
  alignSelfRowCenter: 'align-self-row-center',
  alignSelfRowLeft: 'align-self-row-left',
  alignSelfRowRight: 'align-self-row-right',
  alignSelfRowStretch: 'align-self-row-stretch',
  alignTop: 'align-top',
  alignVerticalCenter: 'align-vertical-center',
  arrow: 'arrow',
  arrowDown: 'arrow-down',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  arrowUp: 'arrow-up',
  ascSort: 'asc-sort',
  at: 'at',
  board: 'board',
  boardsThumbnail: 'boards-thumbnail',
  booleanDifference: 'boolean-difference',
  booleanExclude: 'boolean-exclude',
  booleanFlatten: 'boolean-flatten',
  booleanIntersect: 'boolean-intersect',
  booleanUnion: 'boolean-union',
  brokenLink: 'broken-link',
  bug: 'bug',
  characterA: 'character-a',
  characterB: 'character-b',
  characterC: 'character-c',
  characterD: 'character-d',
  characterE: 'character-e',
  characterF: 'character-f',
  characterG: 'character-g',
  characterH: 'character-h',
  characterI: 'character-i',
  characterJ: 'character-j',
  characterK: 'character-k',
  characterL: 'character-l',
  characterM: 'character-m',
  characterN: 'character-n',
  characterNTilde: 'character-ntilde',
  characterO: 'character-o',
  characterP: 'character-p',
  characterQ: 'character-q',
  characterR: 'character-r',
  characterS: 'character-s',
  characterT: 'character-t',
  characterU: 'character-u',
  characterV: 'character-v',
  characterW: 'character-w',
  characterX: 'character-x',
  characterY: 'character-y',
  characterZ: 'character-z',
  clipContent: 'clip-content',
  clipboard: 'clipboard',
  clock: 'clock',
  close: 'close',
  closeSmall: 'close-small',
  code: 'code',
  column: 'column',
  columnReverse: 'column-reverse',
  comments: 'comments',
  component: 'component',
  componentCopy: 'component-copy',
  constraintHorizontal: 'constraint-horizontal',
  constraintVertical: 'constraint-vertical',
  cornerBottom: 'corner-bottom',
  cornerBottomLeft: 'corner-bottom-left',
  cornerBottomRight: 'corner-bottom-right',
  cornerCenter: 'corner-center',
  cornerRadius: 'corner-radius',
  cornerTop: 'corner-top',
  cornerTopLeft: 'corner-top-left',
  cornerTopRight: 'corner-top-right',
  crown: 'crown',
  curve: 'curve',
  delete: 'delete',
  deleteText: 'delete-text',
  descSort: 'desc-sort',
  detach: 'detach',
  detached: 'detached',
  distributeHorizontally: 'distribute-horizontally',
  distributeVerticalSpacing: 'distribute-vertical-spacing',
  document: 'document',
  download: 'download',
  drop: 'drop',
  dropShadow: 'drop-shadow',
  easingEase: 'easing-ease',
  easingEaseIn: 'easing-ease-in',
  easingEaseInOut: 'easing-ease-in-out',
  easingEaseOut: 'easing-ease-out',
  easingLinear: 'easing-linear',
  effects: 'effects',
  ellipse: 'ellipse',
  exit: 'exit',
  expand: 'expand',
  externalLink: 'external-link',
  eyeOff: 'eye-off',
  feedback: 'feedback',
  fillContent: 'fill-content',
  filter: 'filter',
  fixedWidth: 'fixed-width',
  fitContent: 'fit-content',
  flex: 'flex',
  flexGrid: 'flex-grid',
  flexHorizontal: 'flex-horizontal',
  flexVertical: 'flex-vertical',
  flipHorizontal: 'flip-horizontal',
  flipVertical: 'flip-vertical',
  folder: 'folder',
  gapHorizontal: 'gap-horizontal',
  gapVertical: 'gap-vertical',
  graphics: 'graphics',
  grid: 'grid',
  gridColumn: 'grid-column',
  gridColumns: 'grid-columns',
  gridGutter: 'grid-gutter',
  gridMargin: 'grid-margin',
  gridRow: 'grid-row',
  gridRows: 'grid-rows',
  gridSquare: 'grid-square',
  group: 'group',
  gutterHorizontal: 'gutter-horizontal',
  gutterVertical: 'gutter-vertical',
  help: 'help',
  hide: 'hide',
  history: 'history',
  hsva: 'hsva',
  hugContent: 'hug-content',
  icon: 'icon',
  img: 'img',
  innerShadow: 'inner-shadow',
  info: 'info',
  importExport: 'import-export',
  interaction: 'interaction',
  joinNodes: 'join-nodes',
  justifyContentColumnAround: 'justify-content-column-around',
  justifyContentColumnBetween: 'justify-content-column-between',
  justifyContentColumnCenter: 'justify-content-column-center',
  justifyContentColumnEnd: 'justify-content-column-end',
  justifyContentColumnEvenly: 'justify-content-column-evenly',
  justifyContentColumnStart: 'justify-content-column-start',
  justifyContentRowAround: 'justify-content-row-around',
  justifyContentRowBetween: 'justify-content-row-between',
  justifyContentRowCenter: 'justify-content-row-center',
  justifyContentRowEnd: 'justify-content-row-end',
  justifyContentRowEvenly: 'justify-content-row-evenly',
  justifyContentRowStart: 'justify-content-row-start',
  layers: 'layers',
  library: 'library',
  locate: 'locate',
  lock: 'lock',
  margin: 'margin',
  marginBottom: 'margin-bottom',
  marginLeft: 'margin-left',
  marginLeftRight: 'margin-left-right',
  marginRight: 'margin-right',
  marginTop: 'margin-top',
  marginTopBottom: 'margin-top-bottom',
  mask: 'mask',
  masked: 'masked',
  menu: 'menu',
  mergeNodes: 'merge-nodes',
  move: 'move',
  msgError: 'msg-error',
  msgNeutral: 'msg-neutral',
  msgSuccess: 'msg-success',
  msgWarning: 'msg-warning',
  number: 'number',
  openLink: 'open-link',
  paddingBottom: 'padding-bottom',
  paddingExtended: 'padding-extended',
  paddingLeft: 'padding-left',
  paddingLeftRight: 'padding-left-right',
  paddingRight: 'padding-right',
  paddingTop: 'padding-top',
  paddingTopBottom: 'padding-top-bottom',
  path: 'path',
  pentool: 'pentool',
  percentage: 'percentage',
  picker: 'picker',
  pin: 'pin',
  play: 'play',
  puzzle: 'puzzle',
  rectangle: 'rectangle',
  reload: 'reload',
  remove: 'remove',
  reorder: 'reorder',
  rgba: 'rgba',
  rgbaComplementary: 'rgba-complementary',
  rotation: 'rotation',
  row: 'row',
  rowReverse: 'row-reverse',
  search: 'search',
  separateNodes: 'separate-nodes',
  settings: 'settings',
  shown: 'shown',
  sizeHorizontal: 'size-horizontal',
  sizeVertical: 'size-vertical',
  snapNodes: 'snap-nodes',
  statusAlert: 'status-alert',
  statusTick: 'status-tick',
  statusUpdate: 'status-update',
  statusWrong: 'status-wrong',
  strokeArrow: 'stroke-arrow',
  strokeCircle: 'stroke-circle',
  strokeDiamond: 'stroke-diamond',
  strokeRectangle: 'stroke-rectangle',
  strokeRounded: 'stroke-rounded',
  strokeSize: 'stroke-size',
  strokeSquared: 'stroke-squared',
  strokeTriangle: 'stroke-triangle',
  svg: 'svg',
  swatches: 'swatches',
  switch: 'switch',
  text: 'text',
  textAlignCenter: 'text-align-center',
  textAlignLeft: 'text-align-left',
  textAlignRight: 'text-align-right',
  textAutoHeight: 'text-auto-height',
  textAutoWidth: 'text-auto-width',
  textBottom: 'text-bottom',
  textFixed: 'text-fixed',
  textFontFamily: 'text-font-family',
  textFontSize: 'text-font-size',
  textFontWeight: 'text-font-weight',
  textJustify: 'text-justify',
  textLetterspacing: 'text-letterspacing',
  textLineheight: 'text-lineheight',
  textLowercase: 'text-lowercase',
  textLtr: 'text-ltr',
  textMiddle: 'text-middle',
  textMixed: 'text-mixed',
  textPalette: 'text-palette',
  textParagraph: 'text-paragraph',
  textRtl: 'text-rtl',
  textStroked: 'text-stroked',
  textTop: 'text-top',
  textTypography: 'text-typography',
  textUnderlined: 'text-underlined',
  textUppercase: 'text-uppercase',
  thumbnail: 'thumbnail',
  tick: 'tick',
  tokens: 'tokens',
  toCorner: 'to-corner',
  toCurve: 'to-curve',
  tree: 'tree',
  unlock: 'unlock',
  user: 'user',
  variant: 'variant',
  verticalAlignItemsCenter: 'vertical-align-items-center',
  verticalAlignItemsEnd: 'vertical-align-items-end',
  verticalAlignItemsStart: 'vertical-align-items-start',
  viewAsIcons: 'view-as-icons',
  viewAsList: 'view-as-list',
  wrap: 'wrap'
} as const;

export type IconId = typeof ICON_ID[keyof typeof ICON_ID];

// Helper function to get icon list
export function getIconList(): IconId[] {
  return Object.values(ICON_ID);
}
